---
name: Build containers
on:
  schedule:
    # do the build on Sunday early morning
    - cron: '0 3 * * SUN'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"

jobs:
  build_and_push:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # list of containers to build, same string as container directory name
        container_dir: [
          cockpit-tasks,
        ]

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get build date
        id: build_date
        shell: bash
        run: |
          # YYYY-MM-DD
          BUILD_DATE=$(date --iso-8601)
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Image metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          # Image tags
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.build_date.outputs.BUILD_DATE }}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
          labels: |
            org.opencontainers.image.url=https://github.com/${{ github.repository_owner }}/${{ matrix.container_dir }}
          sep-tags: " "
          sep-annotations: " "

      - name: Build image
        id: buildah_build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./containers/${{ matrix.container_dir }}/Containerfile
          context: |
            ./containers/${{ matrix.container_dir }}/
          image: ${{ matrix.container_dir }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Log into registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ matrix.container_dir }}
          tags: ${{ steps.metadata.outputs.tags }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
